### ISSUE TITLE
No login possible

### ISSUE THREAD

**Issue by Elektroarzt** [capull0/BambuAMSCtrl#1]
Hi capull0 ... got your python script up and running in a docker container. On the login page I try to connect without success. If I try "Europe" setting with my BL Account I get a page showing just "failed". If I use "Local" option and hit the login button just nothing happens. Do you have any hint for me?

<img width="350" alt="image" src="https://github.com/user-attachments/assets/ac74e6ab-8466-40f0-9382-3c1a77a9c079">

Here my docker setup

dockerfile
```
# Basis-Image mit Python 3.10
FROM python:3.10-slim

# Installiere git, um das Repository zu klonen
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Arbeitsverzeichnis im Container erstellen
WORKDIR /app

# Klone das Repository
RUN git clone https://github.com/capull0/BambuAMSCtrl.git .

# Installiere die Abhängigkeiten
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install --no-cache-dir flask_serial
RUN pip install --no-cache-dir qrcode

# Starte die Anwendung
CMD ["python", "app.py"]
```

docker compose
```
version: '3.8'

services:
  bambuamsctrl:
    image: bambuamsctrl:latest  # Verwende hier das erstellte Image
    container_name: bambuamsctrl
    ports:
      - "5020:5000"  # Mappe den Host-Port 5020 auf den Container-Port 5000
    volumes:
      - /volume1/docker/bambuamsctrl:/app  # Mountet den lokalen Ordner ins Container-Verzeichnis /app
    command: ["python", "app.py"]  # Startet die Anwendung
    restart: unless-stopped  # Automatischer Neustart bei Fehlern
```
